### ISSUE TITLE
Fine-tuning details

### ISSUE THREAD

**Issue by stancld** [google-research/longt5#5]
Hello,

First of all, I would like to thank you for this great work and for publishing the LongT5 codebase and pre-trained model checkpoints. As a part of an endeavor to port the model into `transformers` (see https://github.com/huggingface/transformers/pull/16792), we are fine-tuning the model to find out if everything works as expected. Would it be, please, possible to share some more fine-tuning details regarding the length of finetuning - e.g. number of training steps/epochs or so?

Thanks a lot!

**Comment by patrickvonplaten** [comment]
Now also available in Transformers: https://github.com/google-research/longt5/pull/6/files
